// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SQS.API.Data;

#nullable disable

namespace SQS.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260705154326_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("SQS.API.Models.Admin", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("UserId");

                    b.ToTable("admins", (string)null);
                });

            modelBuilder.Entity("SQS.API.Models.Counter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_active");

                    b.Property<string>("Location")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("location");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("counters", (string)null);
                });

            modelBuilder.Entity("SQS.API.Models.CounterService", b =>
                {
                    b.Property<int>("CounterId")
                        .HasColumnType("int")
                        .HasColumnName("counter_id");

                    b.Property<int>("ServiceId")
                        .HasColumnType("int")
                        .HasColumnName("service_id");

                    b.HasKey("CounterId", "ServiceId");

                    b.HasIndex("ServiceId");

                    b.ToTable("counter_services", (string)null);
                });

            modelBuilder.Entity("SQS.API.Models.Customer", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("UserId");

                    b.ToTable("customers", (string)null);
                });

            modelBuilder.Entity("SQS.API.Models.DailySequence", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<short>("LastNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)0)
                        .HasColumnName("last_number");

                    b.Property<DateOnly>("SeqDate")
                        .HasColumnType("date")
                        .HasColumnName("seq_date");

                    b.HasKey("Id");

                    b.HasIndex("SeqDate")
                        .IsUnique();

                    b.ToTable("daily_sequence", (string)null);
                });

            modelBuilder.Entity("SQS.API.Models.Service", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("varchar(5)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("services", (string)null);
                });

            modelBuilder.Entity("SQS.API.Models.Staff", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.Property<int>("Kpi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("kpi");

                    b.Property<string>("Position")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasDefaultValue("Nhân viên")
                        .HasColumnName("position");

                    b.HasKey("UserId");

                    b.ToTable("staffs", (string)null);
                });

            modelBuilder.Entity("SQS.API.Models.Ticket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTime?>("CalledAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("called_at");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("completed_at");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("GuestName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("guest_name");

                    b.Property<int?>("IdCounter")
                        .HasColumnType("int")
                        .HasColumnName("id_counter");

                    b.Property<int?>("IdCustomer")
                        .HasColumnType("int")
                        .HasColumnName("id_customer");

                    b.Property<int>("IdService")
                        .HasColumnType("int")
                        .HasColumnName("id_service");

                    b.Property<int?>("IdStaff")
                        .HasColumnType("int")
                        .HasColumnName("id_staff");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("Waiting")
                        .HasColumnName("status");

                    b.Property<DateOnly>("TicketDate")
                        .HasColumnType("date")
                        .HasColumnName("ticket_date");

                    b.Property<string>("TicketNumber")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("varchar(3)")
                        .HasColumnName("ticket_number");

                    b.HasKey("Id");

                    b.HasIndex("IdCounter");

                    b.HasIndex("IdStaff");

                    b.HasIndex("IdCustomer", "TicketDate")
                        .HasDatabaseName("idx_tickets_customer_date");

                    b.HasIndex("Status", "IdCounter")
                        .HasDatabaseName("idx_tickets_status_counter");

                    b.HasIndex("TicketDate", "Status")
                        .HasDatabaseName("idx_tickets_date_status");

                    b.HasIndex("IdService", "Status", "CreatedAt")
                        .HasDatabaseName("idx_tickets_service_status_created");

                    b.ToTable("tickets", (string)null);
                });

            modelBuilder.Entity("SQS.API.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("address");

                    b.Property<DateOnly?>("Birthday")
                        .HasColumnType("date")
                        .HasColumnName("birthday");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("email");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("role");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("SQS.API.Models.Admin", b =>
                {
                    b.HasOne("SQS.API.Models.User", "User")
                        .WithOne("Admin")
                        .HasForeignKey("SQS.API.Models.Admin", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SQS.API.Models.CounterService", b =>
                {
                    b.HasOne("SQS.API.Models.Counter", "Counter")
                        .WithMany("CounterServices")
                        .HasForeignKey("CounterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SQS.API.Models.Service", "Service")
                        .WithMany("CounterServices")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Counter");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("SQS.API.Models.Customer", b =>
                {
                    b.HasOne("SQS.API.Models.User", "User")
                        .WithOne("Customer")
                        .HasForeignKey("SQS.API.Models.Customer", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SQS.API.Models.Staff", b =>
                {
                    b.HasOne("SQS.API.Models.User", "User")
                        .WithOne("Staff")
                        .HasForeignKey("SQS.API.Models.Staff", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SQS.API.Models.Ticket", b =>
                {
                    b.HasOne("SQS.API.Models.Counter", "Counter")
                        .WithMany("Tickets")
                        .HasForeignKey("IdCounter")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SQS.API.Models.Customer", "Customer")
                        .WithMany("Tickets")
                        .HasForeignKey("IdCustomer")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SQS.API.Models.Service", "Service")
                        .WithMany("Tickets")
                        .HasForeignKey("IdService")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SQS.API.Models.Staff", "Staff")
                        .WithMany("Tickets")
                        .HasForeignKey("IdStaff")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Counter");

                    b.Navigation("Customer");

                    b.Navigation("Service");

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("SQS.API.Models.Counter", b =>
                {
                    b.Navigation("CounterServices");

                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("SQS.API.Models.Customer", b =>
                {
                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("SQS.API.Models.Service", b =>
                {
                    b.Navigation("CounterServices");

                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("SQS.API.Models.Staff", b =>
                {
                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("SQS.API.Models.User", b =>
                {
                    b.Navigation("Admin");

                    b.Navigation("Customer");

                    b.Navigation("Staff");
                });
#pragma warning restore 612, 618
        }
    }
}
